version: "3.7"

services:

  peerflix:
    container_name: STREAMING-peerflix
    image: s8n02/peerflix-server-with-password
    environment:
      - USER=morgan
      - PASSWORD=hiccup
    volumes:
      - ${APP_DATA_DIR}/peerflix:/tmp/torrent-stream
    ports:
      - 9000:9000
    restart: unless-stopped
