version: "3"

services:

  nordvpn:
    container_name: NordVPN
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - USER=Zexm4Y48bqUPpwCburEzHsZ7
      - PASS=FjRJkkBBiwMqESkmKwStMgXy
      - COUNTRY=Netherlands
    image: "azinchen/nordvpn"
    restart: unless-stopped
    ports:
      - 5000:5000

  
      
    
  rapidbay:
    image: shnoobins/rapidbay:latest
    network_mode: "service:nordvpn"
    environment:
      - PASSWORD=safran
      - JACKETT_HOST=http://louloushome.freeboxos.fr:9117
      - JACKETT_API_KEY=pdmcg23fssaq63ilfozr939n8mob7ioe
    restart: unless-stopped


networks:
  mynetwork:                                 
    external: true
  
